# Generated by Django 2.2.3 on 2019-11-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20191104_0040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonorModel',
            new_name='DonorRegistrationModel',
        ),
    ]
