# Generated by Django 2.2.3 on 2019-11-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20191104_0043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonorRegistrationModel',
            new_name='DonorModel',
        ),
    ]
